name: project_structure
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  #State management
  get: ^4.6.6

  #Http Request Api
  http: ^1.2.1
  flutter_slidable: ^4.0.3
  share_plus: ^12.0.1

  #Notification
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^18.0.1
  
  #Storage
  shared_preferences: ^2.2.2
  get_storage: ^2.1.1
  flutter_dotenv: ^5.1.0

  #Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #Image Picker
  image_picker: ^1.2.1

  intl: ^0.20.2

  #Drawing
  signature: ^6.3.0
  path_provider: ^2.1.5
  flutter_quill: ^11.5.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` 
  flutter_lints: ^5.0.0



# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/.env

  # To add custom fonts to your application, add a fonts section here,
  # "family" key with the font family name, and a "fonts" key with a
  fonts:
    - family: KH-REGULAR
      fonts:
        - asset: assets/fonts/Battambang-Regular.ttf
    - family: KH-Bold
      fonts:
        - asset: assets/fonts/Battambang-Bold.ttf
    - family: EN-REGULAR
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: EN-SEMIBOLD
      fonts:
        - asset: assets/fonts/Roboto-SemiBold.ttf
    - family: EN-BOLD
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf



