import 'package:flutter/widgets.dart';
import 'package:get/get.dart';

class AppTranslations extends Translations {
  final locale = const Locale('km', 'KM');
  final fallbackLocale = const Locale('en', 'US');

  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          // General
          'locale': 'en',
          'home': 'HomeScreen',
          'search': 'Search',
          'default_folder_name': 'My Note',
          'folders': 'Folders',
          'more': 'More',
          'focus_track': 'Focus Track',
          'english': 'English',

          // More Screen
          'about': 'About',
          'dark_mode': 'Dark Mode',
          'how_to_use': 'How to Use',
          'change_language': 'Change Language',
          'share_app': 'Share App',
          'recently_deleted': 'Recently Deleted',
          'notification': 'Notification',
          'calendar': 'Calendar',

          // Security
          'change_password': 'Change Password',
          'reset_password': 'Reset Password',
          'forget_password': 'Forget Password',

          // Footer
          'copyright': 'Copyright © 2026 Quick Note App.\nVersion 1.0.0 (6)',

          // Format
          'format': 'Format',
          'text_alignment': 'Text Alignment',
          'text_style': 'Text Style',
          'font_size': 'Font Size',
          'small': 'Small',
          'normal': 'Normal',
          'large': 'Large',
          'huge': 'Huge',
          'table_options': 'Table Options',
          'add_row': 'Add Row',
          'a': 'A',
          'add_column': 'Add Column',
          'delete_table': 'Delete Table',
          'delete_table_confirm': 'Are you sure you want to delete this table?',

          //template
          'choose_template': 'Choose Template',
          'none': 'None',
          'lines': 'Lines',
          'grid': 'Grid',
          'exam_paper': 'Exam Paper',
          'notebook': 'Notebook',
          'to_do_list': 'To-Do List',
          'journal': 'Journal',
          'work': 'Work',
          "exam_preparation": "Exam Preparation",
          "homework": "Homework",
          "daily_note": "Daily Note",

          // Color Picker
          'pick_a_color': 'Pick a color',
          'apply': 'Apply',

          // Media/File Block
          'add_media': 'Add Media',
          'take_photo': 'Take Photo',
          'gallery_image': 'Select Image from Gallery',
          'record_video': 'Record a Video',
          'gallery_video': 'Select Video from Gallery',
          'attach_file': 'Attach File',
          'video_options': 'Video Options',
          'image_options': 'Image Options',
          'scan_text': 'Scan Text',
          'resize': 'Resize',
          'zoom': 'Zoom',
          'remove': 'Remove',
          'voice_note': 'Voice Note',
          'listening': 'Listening',
          'speak_now': 'Speak now...',
          'speech_not_available': 'Speech not available',
          'no_text_detected_in_the_image': 'No text detected in the image.',

          // File Handling Actions
          'file_options': 'File Options',
          'error': 'Error',
          'error_file_empty': 'File path is empty.',
          'error_cannot_open': 'Cannot Open File',
          'error_no_app': 'No compatible application found.',
          'file_not_found': 'File Not Found',

          // Editor
          'title': 'Title',
          'start_typing': 'Start typing...',
          'cancel': 'Cancel',
          'backgrounds': 'Backgrounds',
          'save': 'Save',
          'pin': 'Pin',
          'unpin': 'Unpin',
          'pinned_header': 'Pinned',
          'share': 'Share',
          'move_note': 'Move Note',
          'lock_note': 'Lock Note',
          'delete': 'Delete',
          'edit': 'Edit',

          // Auth / Password
          'create': 'Create',
          'create_new_password': 'Create New Password',
          'create_password_desc': 'Create a secure password to protect your personal notes.',
          'new_password': 'New Password',
          'confirm_password': 'Confirm Password',
          'hint': 'Hint',
          'optional': 'Optional',
          'security_question_verification': 'Security Question Verification',
          'select_security_question': 'Select Security Question',
          'security_answer': 'Security Answer',
          'change_password_desc': 'Update the password to protect your notes.',
          'current_password': 'Current Password',
          'confirm_new_password': 'Confirm New Password',
          'new_hint': 'New Hint',
          'select_question': 'Select Question',
          'enter_your_answer': 'Enter your answer',
          'remove_lock_desc': 'Please enter your current password to remove all protection.',
          'select_option': 'Select option',

          'submit': 'Submit',
          'forget_password_desc': 'Verify your identity using your security question to reset your password.',
          'no_security_question': 'No security question set up.',
          'loading': 'Loading...',
          'selected': 'Selected',

          //create password
          'field_required': 'Field Required',
          'field_required_msg': 'Please fill in the password, security question, and answer.',
          'mismatch': 'Mismatch',
          'mismatch_msg': 'Passwords do not match. Please re-type your password.',
          'security_saved': 'Security settings saved successfully!',
          'db_error_title': 'Database Error',
          'db_error_msg': "We couldn't save your settings. Please try again.",

          //change password
          'not_configured': 'Not Configured',
          'not_configured_msg': 'No password found to change. Please create a password first.',
          'input_required': 'Input Required',
          'input_required_msg': 'New password cannot be empty. Please enter a valid password.',
          'verification_failed_msg': 'The current password you entered is incorrect.',
          'password_updated': 'Password updated successfully.',
          'update_failed': 'Update failed. Please try again.',
          'password_confirm_mismatch': 'New password and confirmation do not match.',

          // Forget
          'answer_required_msg': 'Please enter your security answer.',
          'setup_required': 'Setup Required',
          'setup_required_msg': 'Security recovery has not been configured for this account.',
          'verified_success': 'Identity verified successfully!',
          'verification_failed_answer_msg': 'The answer you entered is incorrect. Please try again.',
          'verify_error': 'An error occurred while verifying. Please try again later.',

          // qustion
          "first_school_question": "What was the name of your first school?",
          "mother_maiden_name_question": "What is your mother's maiden name?",
          "birth_city_question": "In which city were you born?",
          "dream_job_child_question": "What was your dream job as a child?",
          "favorite_teacher_question": "What is your favorite teacher's name?",

          // remove
          'no_password_set_msg': 'No password is currently set.',
          'current_password_wrong_msg': 'Current password is incorrect.',
          'password_mismatch_msg': 'Passwords do not match.',
          'security_removed_success': 'Security removed and all notes unlocked.',
          'security_remove_failed': 'Failed to remove security. Please try again.',

          // Folder
          'create_folder': 'Create Folder',
          'update_folder': 'Update Folder',
          'folder_name': 'Folder Name',
          'duplicate_name': 'Duplicate Name',
          'folder_exists': 'A folder with this name already exists.',
          'ok': 'OK',
          'previous': 'Previous',
          'close': 'Close',
          'skip': 'Skip',
          'next': 'Next',
          'tap_to_search': 'Tap to search',
          'tap_to_create_note': 'Tap here to create a new note',
          'tap_to_my_folder': 'Tap folders to view notes',

          // Multi-Selection / Bulk actions inside specific folders
          'deleted_on': 'Deleted on:',
          'notes_selected': '{{count}} selected',
          'locked_notes_bulk_delete_warning': 'Some selected notes are locked. Enter password to delete all.',
          'locked_notes_bulk_move_warning': 'Enter your password to move locked notes.',
          'enter_password_move_note': 'Enter your password to move this locked note.',
          'delete_notes_bulk_confirm': 'Are you sure you want to delete selected notes?',

          // Create Note Screen
          'create_note': 'Create Note',
          'edit_note': 'Edit Note',
          'unlock_note': 'Unlock Note',
          'delete_note': 'Delete Note',
          'delete_note_confirm': 'Are you sure you want to delete this note?',
          'move_to_folder': 'Move to Folder',
          'enter_password_unlock': 'Please enter your password to unlock this note.',
          'remove_protection_desc': 'Please enter your password to remove protection.',
          'verify': 'Verify',
          'password': 'Password',
          'text': 'Text',
          'photos': 'Photos',
          'file_txt': 'File (txt)',
          'untitled': 'Untitled',

          // Folder security
          'folder': 'Folder',
          'lock': 'Lock',
          'unlock': 'Unlock',
          'locked_notes': 'Locked Notes',
          'locked_note': 'Locked Note',
          'lock_folder': 'Lock Folder',
          'unlock_folder': 'Unlock Folder',
          'verify_password': 'Verify Password',
          'delete_folder': 'Delete Folder',
          'locked_folder': 'Locked Folder',
          'enter_password_unlock_folder': 'Please enter your password to unlock.',
          'enter_password_edit_folder': 'Please enter your password to edit.',
          'delete_folder_confirm': 'Are you sure you want to delete ?',
          'locked_folder_with_notes': 'This folder contains locked notes. Enter password to delete everything.',
          'locked_folder_no_notes': 'Please enter your password to delete.',
          'verification_failed': 'Verification Failed',
          'incorrect_password': 'Incorrect Password',
          'access_denied': 'Access Denied',
          'no_folders_yet': 'No folders yet',
          'no_matching_folders': 'No matching folders found',
          'view_note_locked_desc': 'Please enter your password to view this note.',
          'delete_locked_note_desc': 'Please enter your password to delete this locked note.',
          'delete_folder_confirm_subtitle': 'Are you sure you want to delete ? All notes inside will be moved directly to Recently Deleted.',

          //recently deleted
          'restore': 'Restore',
          'move': 'Move',
          'delete_permanently': 'Delete Permanently',
          'restore_to_folder': 'Restore to Folder',
          'perm_delete_confirm': 'Are you sure you want to permanently delete this note? This action cannot be undone.',
          'no_folders_available': 'No folders available',
          'success': 'Success',
          'delete_bulk_confirm_subtitle': 'Are you sure you want to delete selected items forever? This cannot be undone.',
          'today': 'Today',
          'yesterday': 'Yesterday',
          'earlier': 'Earlier',
          'exit_app': 'Exit App',
          'exit_app_confirm': 'Are you sure you want to exit the app?',
          'yes': 'Yes',
          'no_data': 'No data',

          // Timer
          'stopwatch': 'Stopwatch',
          'timer': 'Timer',
          'duration': 'Duration',
          'quick_presets': 'Quick Presets',
          'add_quick_preset': 'Add Quick Preset',
          'save_preset': 'Save Preset',
          'new_timer': 'New Timer',
          'edit_timer': 'Edit Timer',
          'already_exists': 'Already Exists',
          'preset_exists_msg': 'This time is already available in your presets.',
          'duration_zero_msg': 'Duration cannot be zero.',
          'duplicate_timer_msg': 'A timer with this duration and name already exists.',
          'timer_default_label': 'Timer',
          'lap': 'Lap',
          'lap_time': 'Lap Time',
          'label': 'Label',
          'no_time': 'No timer',
          'running': 'Running',
          'recents': 'Recents',
          'total': 'total',
          'timer_finished': 'Timer Finished',
          'has_completed': 'Completed',
          'duplicate': 'Duplicate',
          'delete_timer': 'Delete Timer',
          'delete_timer_confirm': 'Are you sure you want to delete this timer?',
          's': 's',
          'm': 'm',
          'h': 'h',
          'default_sound': 'Default',
          'morning_sound': 'Morning',
          'evening_sound': 'Evening',

          // How to Use
          'how_to_use_title': 'How To Use Quick Note',
          'how_to_use_desc': 'Master your notes with simple steps.',
          'step_01_title': 'Create Your First Note',
          'step_01_desc': 'Tap the \'+\' button to quickly create notes.',
          'step_02_title': 'Organize with Folders',
          'step_02_desc': 'Group your notes into folders like Homework or Projects.',
          'step_03_title': 'Secure Your Notes',
          'step_03_desc': 'Lock important notes to protect private information.',
          'step_04_title': 'Study with Stopwatch',
          'step_04_desc': 'Track your study time and improve focus.',

          // About
          'about_app_name': 'Quick Note App',
          'about_slogan': 'Study smarter, stay organized',
          'about_version': 'Version 1.0.0',
          'about_application': 'About Application',
          'about_description': 'Quick Note App helps students organize notes, manage study materials, and improve productivity through a clean, simple, and modern experience.',
          'about_features': 'Features',
          'about_create_notes': 'Create Notes',
          'about_create_notes_sub': 'Write and save study notes easily',
          'about_edit_anytime': 'Edit Anytime',
          'about_edit_anytime_sub': 'Update notes whenever needed',
          'about_study_smarter': 'Study Smarter',
          'about_study_smarter_sub': 'Organize subjects and materials',
          'contact_email': 'Email',
          'contact_website': 'Website',
          'copyright_footer': '© 2026 Quick Note App',

          // Exams / Tabs
          'exams': 'Exams',
          'upcoming': 'Upcoming',
          'completed': 'Completed',
          'add_exam': 'Add Exam',
          'exam_title': 'Exam Title',
          'location': 'Location',
          'please_provide_exam_title': 'Please provide an Exam Title',
          'no_checklist_items': 'No checklist items added.',
          'no_tracking_modules': 'No tracking modules added yet.',
          'revision_checklist': 'Revision Checklist',
          'add_revision_topic': 'Add Revision Topic',
          'topic_name': 'Topic Name',
          'add_topic': 'Add Topic',
          'exam_details': 'Exam Details',
          'view_revision_checklist': 'View Revision Checklist',
          'date': 'Date',
          'time': 'Time',
          'reminder': 'Reminder',
        },
        'km_KM': {
          // General
          'more': 'បន្ថែម',
          'focus_track': 'ការផ្ដោតអារម្មណ៍',
          'locale': 'km',
          'home': 'ទំព័រដើម',
          'search': 'ស្វែងរក',
          'default_folder_name': 'កំណត់ត្រារបស់ខ្ញុំ',
          'folders': 'ថតឯកសារ',
          'khmer': 'ភាសាខ្មែរ',

          // More Screen
          'about': 'អំពីកម្មវិធី',
          'dark_mode': 'ទម្រង់ពេលយប់',
          'how_to_use': 'របៀបប្រើប្រាស់',
          'change_language': 'ផ្លាស់ប្ដូរភាសា',
          'share_app': 'ចែករំលែកកម្មវិធី',
          'recently_deleted': 'បានលុបថ្មីៗ',
          'notification': 'ការជូនដំណឹង',
          'calendar': 'ប្រតិទិន',

          // Security
          'change_password': 'ផ្លាស់ប្ដូរពាក្យសម្ងាត់',
          'reset_password': 'កំណត់ពាក្យសម្ងាត់ឡើងវិញ',
          'forget_password': 'ភ្លេចពាក្យសម្ងាត់',

          // Footer
          'copyright': 'រក្សាសិទ្ធិ © ២០២៦ កម្មវិធី Quick Note\nកំណែ ១.០.០ (៦)',

          // Format
          'format': 'ទម្រង់',
          'text_alignment': 'តម្រឹមអត្ថបទ',
          'text_style': 'រចនាប័ទ្មអត្ថបទ',
          'font_size': 'ទំហំអក្សរ',
          'small': 'តូច',
          'normal': 'ធម្មតា',
          'large': 'ធំ',
          'huge': 'ធំខ្លាំង',
          'table_options': 'ជម្រើសតារាង',
          'add_row': 'បន្ថែមជួរដេក',
          'add_column': 'បន្ថែមជួរឈរ',
          'delete_table': 'លុបតារាង',
          'delete_table_confirm': 'តើអ្នកពិតជាចង់លុបតារាងនេះមែនទេ?',
          'a': 'ក',

          //template
          'choose_template': 'ជ្រើសរើស​គំរូ',
          'none': 'គ្មាន',
          'lines': 'បន្ទាត់',
          'grid': 'ក្រឡាចត្រង្គ',
          'exam_paper': 'ក្រដាសប្រឡង',
          'notebook': 'សៀវភៅកំណត់ត្រា',
          'to_do_list': 'បញ្ជីការងារ',
          'journal': 'កំណត់ហេតុ',
          'work': 'ការងារ',
          "exam_preparation": "ការត្រៀមប្រឡង",
          "homework": "កិច្ចការផ្ទះ",
          "daily_note": "កំណត់ត្រាប្រចាំថ្ងៃ",

          // Color Picker
          'pick_a_color': 'ជ្រើសរើសពណ៌',
          'apply': 'យល់ព្រម',

          // Media/File Block
          'add_media': 'បន្ថែមមេឌៀ',
          'take_photo': 'ថតរូប',
          'gallery_image': 'ជ្រើសរើសរូបភាពពីវិចិត្រសាល',
          'record_video': 'ថតវីដេអូ',
          'gallery_video': 'ជ្រើសរើសវីដេអូពីវិចិត្រសាល',
          'attach_file': 'ភ្ជាប់ឯកសារ',
          'video_options': 'ជម្រើសវីដេអូ',
          'image_options': 'ជម្រើសរូបភាព',
          'scan_text': 'អត្ថបទស្កេន',
          'resize': 'កែទំហំ',
          'zoom': 'ពង្រីក',
          'remove': 'លុបចេញ',
          'voice_note': 'កំណត់ត្រាជាសំឡេង',
          'listening': 'ការស្តាប់',
          'speak_now': 'និយាយឥឡូវនេះ...',
          'speech_not_available': 'មិនអាចនិយាយបាន',
          'no_text_detected_in_the_image': 'រកមិនឃើញអក្សរនៅក្នុងរូបភាពទេ។',

          // File Handling Actions
          'file_options': 'ជម្រើសឯកសារ',
          'error': 'កំហុស',
          'error_file_empty': 'ផ្លូវឯកសារទទេ ។',
          'error_cannot_open': 'មិនអាចបើកឯកសារបានទេ',
          'error_no_app': 'រកមិនឃើញកម្មវិធីសម្រាប់បើកឯកសារនេះទេ។',
          'file_not_found': 'រកមិនឃើញឯកសារ',

          // Editor
          'title': 'ចំណងជើង',
          'start_typing': 'ចាប់ផ្តើមវាយអត្ថបទ...',
          'cancel': 'បោះបង់',
          'backgrounds': 'ផ្ទៃខាងក្រោយ',
          'save': 'រក្សាទុក',
          'pin': 'បិទភ្ជាប់',
          'unpin': 'ដកការបិទភ្ជាប់',
          'pinned_header': 'បានបិទភ្ជាប់',
          'share': 'ចែករំលែក',
          'move_note': 'ផ្លាស់ប្តូរកំណត់ត្រា',
          'lock_note': 'ចាក់សោកំណត់ត្រា',
          'delete': 'លុប',
          'edit': 'កែប្រែ',

          // Auth / Password
          'create': 'បង្កើត',
          'create_new_password': 'បង្កើតពាក្យសម្ងាត់ថ្មី',
          'create_password_desc': 'បង្កើតពាក្យសម្ងាត់ដែលមានសុវត្ថិភាព ដើម្បីការពារកំណត់ត្រាផ្ទាល់ខ្លួនរបស់អ្នក។',
          'new_password': 'ពាក្យសម្ងាត់ថ្មី',
          'confirm_password': 'បញ្ជាក់ពាក្យសម្ងាត់',
          'hint': 'ចំណាំជំនួយ',
          'optional': 'ជម្រើស',
          'security_question_verification': 'សំណួរសុវត្ថិភាពសម្រាប់ផ្ទៀងផ្ទាត់',
          'select_security_question': 'ជ្រើសរើសសំណួរសុវត្ថិភាព',
          'security_answer': 'ចម្លើយសុវត្ថិភាព',
          'change_password_desc': 'ធ្វើបច្ចុប្បន្នភាពពាក្យសម្ងាត់ ដើម្បីការពារកំណត់ត្រារបស់អ្នក។',
          'current_password': 'ពាក្យសម្ងាត់បច្ចុប្បន្ន',
          'confirm_new_password': 'បញ្ជាក់ពាក្យសម្ងាត់ថ្មី',
          'new_hint': 'ចំណាំជំនួយថ្មី',
          'select_question': 'ជ្រើសរើសសំណួរ',
          'enter_your_answer': 'បញ្ចូលចម្លើយរបស់អ្នក',
          'remove_lock_desc': 'សូមបញ្ចូលពាក្យសម្ងាត់បច្ចុប្បន្នរបស់អ្នក ដើម្បីដកការការពារទាំងអស់។',
          'submit': 'បញ្ជូន',
          'select_option': 'ជ្រើសរើសជម្រើស',

          //create password
          'forget_password_desc': 'ផ្ទៀងផ្ទាត់អត្តសញ្ញាណរបស់អ្នកដោយប្រើសំណួរសុវត្ថិភាព ដើម្បីកំណត់ពាក្យសម្ងាត់ឡើងវិញ។',
          'no_security_question': 'មិនទាន់បានកំណត់សំណួរសុវត្ថិភាពទេ',
          'loading': 'កំពុងផ្ទុក...',
          'selected': 'បានជ្រើសរើស',
          'field_required': 'ត្រូវការបំពេញព័ត៌មាន',
          'field_required_msg': 'សូមបំពេញពាក្យសម្ងាត់ សំណួរសុវត្ថិភាព និងចម្លើយ។',
          'mismatch': 'មិនត្រូវគ្នា',
          'mismatch_msg': 'ពាក្យសម្ងាត់មិនត្រូវគ្នា សូមបញ្ចូលឡើងវិញ។',
          'security_saved': 'ការកំណត់សុវត្ថិភាពបានរក្សាទុកជោគជ័យ!',
          'db_error_title': 'កំហុសមូលដ្ឋានទិន្នន័យ',
          'db_error_msg': 'មិនអាចរក្សាទុកការកំណត់បានទេ។ សូមព្យាយាមម្តងទៀត។',

          //Change pasword
          'not_configured': 'មិនបានកំណត់',
          'not_configured_msg': 'រកមិនឃើញពាក្យសម្ងាត់។ សូមបង្កើតពាក្យសម្ងាត់ជាមុន។',
          'input_required': 'ត្រូវការបញ្ចូល',
          'input_required_msg': 'ពាក្យសម្ងាត់ថ្មីមិនអាចទទេបានទេ។ សូមបញ្ចូល។',
          'verification_failed': 'បរាជ័យការផ្ទៀងផ្ទាត់',
          'verification_failed_msg': 'ពាក្យសម្ងាត់បច្ចុប្បន្នមិនត្រឹមត្រូវ។',
          'password_updated': 'បានធ្វើបច្ចុប្បន្នភាពពាក្យសម្ងាត់ជោគជ័យ។',
          'update_failed': 'បរាជ័យក្នុងការអាប់ដេត សូមព្យាយាមម្ដងទៀត។',
          'password_confirm_mismatch': 'ពាក្យសម្ងាត់ថ្មី និងការបញ្ជាក់មិនត្រូវគ្នា។',

          // Forget
          'answer_required_msg': 'សូមបញ្ចូលចម្លើយសុវត្ថិភាព។',
          'setup_required': 'ត្រូវការកំណត់ជាមុន',
          'setup_required_msg': 'ការសង្គ្រោះសុវត្ថិភាពមិនទាន់បានកំណត់សម្រាប់គណនីនេះទេ។',
          'verified_success': 'បានផ្ទៀងផ្ទាត់អត្តសញ្ញាណជោគជ័យ!',
          'verification_failed_title': 'បរាជ័យការផ្ទៀងផ្ទាត់',
          'verification_failed_answer_msg': 'ចម្លើយដែលអ្នកបញ្ចូលមិនត្រឹមត្រូវ។ សូមព្យាយាមម្តងទៀត។',
          'verify_error': 'មានបញ្ហាក្នុងការផ្ទៀងផ្ទាត់។ សូមព្យាយាមម្តងទៀតក្រោយ។',

          //Qustion
          "first_school_question": "តើសាលាដំបូងរបស់អ្នកមានឈ្មោះអ្វី?",
          "mother_maiden_name_question": "តើនាមត្រកូលពីកំណើតរបស់ម្តាយអ្នកជាអ្វី?",
          "birth_city_question": "តើអ្នកកើតនៅទីក្រុងណា?",
          "dream_job_child_question": "តើការងារក្នុងក្តីស្រមៃរបស់អ្នកនៅពេលកុមារគឺអ្វី?",
          "favorite_teacher_question": "តើគ្រូដែលអ្នកចូលចិត្តបំផុតមានឈ្មោះអ្វី?",

          // remove
          'no_password_set_msg': 'មិនមានពាក្យសម្ងាត់នៅឡើយទេ។',
          'current_password_wrong_msg': 'ពាក្យសម្ងាត់បច្ចុប្បន្នមិនត្រឹមត្រូវ។',
          'password_mismatch_msg': 'ពាក្យសម្ងាត់មិនត្រូវគ្នា។',
          'security_removed_success': 'បានលុបសុវត្ថិភាព និងដោះសោទាំងអស់ជោគជ័យ។',
          'security_remove_failed': 'បរាជ័យក្នុងការលុបសុវត្ថិភាព សូមព្យាយាមម្ដងទៀត។',

          // Folder
          'create_folder': 'បង្កើតថតឯកសារ',
          'update_folder': 'កែប្រែថតឯកសារ',
          'folder_name': 'ឈ្មោះថតឯកសារ',
          'duplicate_name': 'ឈ្មោះស្ទួន',
          'folder_exists': 'មានថតឯកសារដែលមានឈ្មោះនេះរួចហើយ។',
          'ok': 'យល់ព្រម',
          'previous': 'ត្រឡប់ក្រោយ',
          'close': 'បិទ',
          'skip': 'រំលង',
          'next': 'បន្ទាប់',
          'tap_to_search': 'ចុចដើម្បីស្វែងរក',
          'tap_to_create_note': 'ចុចទីនេះដើម្បីបង្កើតកំណត់ត្រាថ្មី',
          'tap_to_my_folder': 'ចុចថតឯកសារដើម្បីមើលកំណត់ចំណាំ',

          // Multi-Selection / Bulk actions inside specific folders
          'deleted_on': 'បានលុបនៅថ្ងៃទី៖',
          'notes_selected': 'បានជ្រើសរើស',
          'locked_notes_bulk_delete_warning': 'កំណត់ត្រាដែលបានជ្រើសរើសមួយចំនួនត្រូវបានចាក់សោ។ សូមបញ្ចូលពាក្យសម្ងាត់ដើម្បីលុបទាំងអស់។',
          'locked_notes_bulk_move_warning': 'សូមបញ្ចូលពាក្យសម្ងាត់របស់អ្នក ដើម្បីផ្លាស់ប្ដូរកំណត់ត្រាដែលបានចាក់សោ។',
          'enter_password_move_note': 'សូមបញ្ចូលពាក្យសម្ងាត់របស់អ្នក ដើម្បីផ្លាស់ប្តូរកំណត់ត្រាដែលបានចាក់សោនេះ។',
          'delete_notes_bulk_confirm': 'តើអ្នកពិតជាចង់លុបកំណត់ត្រាដែលបានជ្រើសរើសទាំង នេះមែនទេ?',

          // Create Note Screen
          'create_note': 'បង្កើតកំណត់ត្រា',
          'edit_note': 'កែប្រែកំណត់ត្រា',
          'delete_note': 'លុបកំណត់ត្រា',
          'delete_note_confirm': 'តើអ្នកពិតជាចង់លុបកំណត់ត្រានេះមែនទេ?',
          'move_to_folder': 'ផ្លាស់ប្ដូរទៅថតឯកសារ',
          'unlock_note': 'ដោះសោកំណត់ត្រា',
          'verify': 'ផ្ទៀងផ្ទាត់',
          'enter_password_unlock': 'សូមបញ្ចូលពាក្យសម្ងាត់ដើម្បីដោះសោ។',
          'remove_protection_desc': 'សូមបញ្ចូលពាក្យសម្ងាត់របស់អ្នកដើម្បីដកការការពារ។',
          'password': 'ពាក្យសម្ងាត់',
          'text': 'អត្ថបទ',
          'photos': 'រូបថត',
          'file_txt': 'ឯកសារ (txt)',
          'lock': 'ចាក់សោ',
          'untitled': 'គ្មានចំណងជើង',

          // Folder security
          'folder': 'ថតឯកសារ',
          'unlock': 'ដោះសោ',
          'lock_folder': 'ចាក់សោថតឯកសារ',
          'locked_notes': 'កំណត់ត្រាដែលបានចាក់សោ',
          'locked_note': 'កំណត់ត្រាដែលបានចាក់សោ',
          'unlock_folder': 'ដោះសោថតឯកសារ',
          'verify_password': 'ផ្ទៀងផ្ទាត់ពាក្យសម្ងាត់',
          'delete_folder': 'លុបថតឯកសារ',
          'locked_folder': 'ថតឯកសារត្រូវបានចាក់សោ',
          'enter_password_unlock_folder': 'សូមបញ្ចូលបពាក្យសម្ងាត់របស់អ្នកដើម្បីដោះសោ',
          'enter_password_edit_folder': 'សូមបញ្ចូលពាក្យសម្ងាត់របស់អ្នកដើម្បីកែប្រែ',
          'delete_folder_confirm': 'តើអ្នកពិតជាចង់លុប មែនទេ?',
          'locked_folder_with_notes': 'ថតនេះមានកំណត់ត្រាដែលបានចាក់សោ។ សូមបញ្ចូលពាក្យសម្ងាត់ដើម្បីលុបទាំងអស់។',
          'locked_folder_no_notes': 'សូមបញ្ចូលពាក្យសម្ងាត់របស់អ្នកដើម្បីលុប។',
          'incorrect_password': 'ពាក្យសម្ងាត់មិនត្រឹមត្រូវទេ',
          'access_denied': 'ការចូលប្រើត្រូវបានបដិសេធ',
          'no_folders_yet': 'មិនទាន់មានថតឯកសារទេ',
          'no_matching_folders': 'រកមិនឃើញថតឯកសារដែលត្រូវគ្នាទេ',
          'view_note_locked_desc': 'សូមបញ្ចូលពាក្យសម្ងាត់ដើម្បីមើលកំណត់ត្រានេះ។',
          'delete_locked_note_desc': 'សូមបញ្ចូលពាក្យសម្ងាត់ដើម្បីលុបកំណត់ត្រាដែលបានចាក់សោនេះ។',
          'delete_folder_confirm_subtitle': 'តើអ្នកប្រាកដជាចង់លុបមែនទេ? រាល់កំណត់ត្រានៅខាងក្នុងនឹងត្រូវផ្លាស់ប្ដូរទៅកាន់បានលុបថ្មីៗ។',

          //recently deleted
          'restore': 'ស្ដារ',
          'move': 'ផ្លាស់ប្តូរ',
          'delete_permanently': 'លុបជាអចិន្ត្រៃយ៍',
          'restore_to_folder': 'ស្ដារទៅកាន់ថតឯកសារ',
          'perm_delete_confirm': 'តើអ្នកប្រាកដជាចង់លុបកំណត់ត្រានេះជាអចិន្ត្រៃយ៍មែនទេ? សកម្មភាពនេះមិនអាចបញ្ច្រាសបានទេ។',
          'no_folders_available': 'មិនមានថតឯកសារទេ',
          'success': 'ជោគជ័យ',
          'delete_bulk_confirm_subtitle': 'តើអ្នកប្រាកដជាចង់លុបកំណត់ត្រាចំនួនដែលបានជ្រើសរើសចោលជារៀងរហូតមែនទេ? សកម្មភាពនេះមិនអាចស្ដារឡើងវិញបានទេ។',
          'today': 'ថ្ងៃនេះ',
          'yesterday': 'ម្សិលមិញ',
          'earlier': 'ពីមុន',
          'exit_app': 'ចាកចេញពីកម្មវិធី',
          'exit_app_confirm': 'តើអ្នកពិតជាចង់ចាកចេញពីកម្មវិធីមែនទេ?',
          'yes': 'បាទ/ចាស',
          'no_data': 'គ្មានទិន្នន័យ',

          // Timer
          'stopwatch': 'នាឡិកា​កំណត់​ពេល',
          'timer': 'ម៉ោង',
          'duration': 'រយៈពេល',
          'quick_presets': 'ការកំណត់ទុកជាមុន',
          'add_quick_preset': 'បន្ថែមការកំណត់រហ័ស',
          'save_preset': 'រក្សាទុកការកំណត់',
          'new_timer': 'កំណត់ម៉ោងថ្មី',
          'edit_timer': 'កែប្រែកំណត់ម៉ោង',
          'already_exists': 'មានរួចហើយ',
          'preset_exists_msg': 'ពេលវេលានេះមាននៅក្នុងបញ្ជីកំណត់រួចហើយ។',
          'duration_zero_msg': 'រយៈពេលមិនអាចសូន្យបានទេ។',
          'duplicate_timer_msg': 'ការកំណត់ម៉ោងដែលមានឈ្មោះ និងរយៈពេលនេះរួចហើយ។',
          'timer_default_label': 'កំណត់ម៉ោង',
          'lap': 'ជុំ',
          'lap_time': 'រយៈពេលជុំ',
          'label': 'ស្លាកឈ្មោះ',
          'no_time': 'មិនមានការកំណត់ម៉ោងទេ',
          'running': 'កំពុងដំណើរការ',
          'recents': 'ប្រវត្តិថ្មីៗ',
          'total': 'សរុប',
          'duplicate': 'ស្ទួន',
          'timer_finished': 'កំណត់ម៉ោងបានបញ្ចប់',
          'has_completed': 'បានបញ្ចប់',
          'delete_timer': 'លុបការកំណត់ម៉ោង',
          'delete_timer_confirm': 'តើអ្នកពិតជាចង់លុបការកំណត់ម៉ោងនេះមែនទេ?',
          's': 'វិ',
          'm': 'ន',
          'h': 'ម',
          'default_sound': 'លំនាំដើម',
          'morning_sound': 'ពេលព្រឹក',
          'evening_sound': 'ពេលល្ងាច',

          // How to Use
          'step': 'ជំហានទី',
          'how_to_use_title': 'របៀបប្រើប្រាស់កម្មវិធី',
          'how_to_use_desc': 'គ្រប់គ្រងកំណត់ត្រារបស់អ្នកដោយជំហានងាយៗ។',
          'step_01_title': 'បង្កើតកំណត់ត្រាដំបូង',
          'step_01_desc': 'ចុចប៊ូតុង \'+\' ដើម្បីបង្កើតកំណត់ត្រាយ៉ាងរហ័ស។',
          'step_02_title': 'រៀបចំដោយប្រើថតឯកសារ',
          'step_02_desc': 'ដាក់កំណត់ត្រារបស់អ្នកទៅក្នុងថតឯកសារ ដូចជា កិច្ចការផ្ទះ ឬគម្រោង។',
          'step_03_title': 'ការពារកំណត់ត្រារបស់អ្នក',
          'step_03_desc': 'ចាក់សោកំណត់ត្រាសំខាន់ៗ ដើម្បីការពារព័ត៌មានផ្ទាល់ខ្លួន។',
          'step_04_title': 'សិក្សាដោយប្រើនាឡិកាកំណត់ពេល',
          'step_04_desc': 'តាមដានពេលវេលាសិក្សារបស់អ្នក និងបង្កើនការផ្ដោតអារម្មណ៍។',

          // About
          'about_app_name': 'កម្មវិធី Quick Note',
          'about_slogan': 'សិក្សាកាន់តែឆ្លាតវៃ រៀបចំបានល្អប្រសើរ',
          'about_version': 'កំណែ ១.០.០',
          'about_application': 'អំពីកម្មវិធី',
          'about_description': 'កម្មវិធី Quick Note ជួយសិស្សានុសិស្សក្នុងការរៀបចំកំណត់ត្រា និងបង្កើនផលិតភាពតាមរយៈបទពិសោធន៍ដ៏សាមញ្ញ និងទំនើប។',
          'about_features': 'លក្ខណៈពិសេស',
          'about_create_notes': 'បង្កើតកំណត់ត្រា',
          'about_create_notes_sub': 'សរសេរ និងរក្សាទុកកំណត់ត្រាសិក្សាបានយ៉ាងងាយស្រួល',
          'about_edit_anytime': 'កែសម្រួលគ្រប់ពេល',
          'about_edit_anytime_sub': 'កែសម្រួលកំណត់ត្រាគ្រប់ពេលដែលអ្នកត្រូវការ',
          'about_study_smarter': 'សិក្សាកាន់តែឆ្លាតវៃ',
          'about_study_smarter_sub': 'រៀបចំមុខវិជ្ជា និងសម្ភារៈសិក្សាឱ្យមានរបៀប',
          'contact_email': 'អ៊ីមែល',
          'contact_website': 'គេហទំព័រ',
          'copyright_footer': '© ២០២៦ កម្មវិធី Quick Note',

          // Exams / Tabs
          'exams': 'ការប្រឡង',
          'upcoming': 'ជិតមកដល់',
          'completed': 'បានបញ្ចប់',
          'add_exam': 'បន្ថែមការប្រឡង',
          'exam_title': 'ចំណងជើងការប្រឡង',
          'location': 'ទីតាំង',
          'please_provide_exam_title': 'សូមបញ្ចូលចំណងជើងការប្រឡង',
          'no_checklist_items': 'មិនទាន់មានបញ្ជីផ្ទៀងផ្ទាត់ត្រូវបានបន្ថែមទេ។',
          'no_tracking_modules': 'មិនទាន់មានម៉ូឌុលតាមដានត្រូវបានបន្ថែមទេ។',
          'revision_checklist': 'បញ្ជីផ្ទៀងផ្ទាត់ការរំលឹកមេរៀន',
          'add_revision_topic': 'បន្ថែមប្រធានបទរំលឹកមេរៀន',
          'topic_name': 'ឈ្មោះប្រធានបទ',
          'add_topic': 'បន្ថែមប្រធានបទ',
          'exam_details': 'ព័ត៌មានលម្អិតការប្រឡង',
          'view_revision_checklist': 'មើលបញ្ជីផ្ទៀងផ្ទាត់ការរំលឹកមេរៀន',
          'date': 'កាលបរិច្ឆេទ',
          'time': 'ម៉ោង',
          'reminder': 'ការរំលឹក',
        },
      };
}
